CONFIG_ZMK_POINTING=y
CONFIG_BT_DEVICE_NAME="XIAO Trackpad"
CONFIG_ZMK_BLE_INIT_PRIORITY=40
CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=y
# Aktivera USB och loggning för felsökning
CONFIG_USB=y
CONFIG_USB_DEVICE_STACK=y
CONFIG_UART_CONSOLE=y
CONFIG_LOG=y
CONFIG_ZMK_USB_LOGGING=y
