manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: azoteq-remote
      url-base: https://github.com/AYM1607
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: zmk-driver-azoteq-iqs5xx
      remote: azoteq-remote
      revision: main
      path: zmk-driver-azoteq-iqs5xx
  self:
    path: config
